### ISSUE TITLE
The Wavenumber calibration won't be saved

### ISSUE THREAD

**Issue by WeiWenKevinChen** [CCampJr/CRIkit2#44] opened 2018-05-11 20:04 UTC
I have to re-do the wavenumber calibration every time

**Comment by CCampJr** [comment] 2018-07-06 04:29
Possible duplicate of #60

**Comment by CCampJr** [comment] 2018-07-06 04:30
@WeiWenKevinChen  -- that's just an internal comment to myself -- ignore it

**Comment by CCampJr** [comment] 2019-05-21 19:39
Fixed in #60

**Closed by CCampJr** 2019-05-21 19:39 UTC
Labels: important
